### PR TITLE
Prevent default browser actions on CTRL+K

### LINKED ISSUE #153: [FF] Browser steals selection on CLTR+K
### Steps to reproduce

1. Open a sample, for example: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/balloon-editor.html
2. Select some text.
3. Press <kbd>Ctrl</kbd> + <kbd>K</kbd> to open link balloon.

### Expected result

Field in balloon is focused.

### Current result

Browser steals selection and focuses in search bar.

### Notes

I think this is because we cannot cancel default event.

### LINKED ISSUE #154: [Edge] Browser opens another tab with cloned URL after CTRL+K
## Steps to reproduce

1. Open a sample, e.g. https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/image.html
2. Click Ctrl+K

Browser: Edge 15

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Prevented default browser actions on CTRL+K. Closes #153. Closes #154.

### CODE REVIEW

File: tests/link.js [hunk 1]
```diff
@@ -442,14 +442,39 @@ describe( 'Link', () => {
...
+			editor.keystrokes.press( {
+				keyCode: keyCodes.k,
+				ctrlKey: true,
+				preventDefault: sinon.spy(),
+				stopPropagation: sinon.spy()
+			} );
 			sinon.assert.calledWithExactly( spy, true );
 		} );
 
+		it( 'should show prevent default actions on Ctrl+K keystroke', () => {
```
Comment (Reinmar) [inline tests/link.js]: wrong desc

File: src/link.js [hunk 2]
```diff
@@ -132,7 +132,11 @@ export default class Link extends Plugin {
 		const t = editor.t;
 
 		// Handle the `Ctrl+K` keystroke and show the panel.
-		editor.keystrokes.set( linkKeystroke, () => {
+		editor.keystrokes.set( linkKeystroke, ( keyEvtData, cancel ) => {
+			// Stop the event in the DOM to prevent default browser action.
```
Comment (Reinmar) [inline src/link.js]: It's more about preventing.

```
// Prevent focusing the search bar. #TICKETNUMBER
```
