### PR TITLE
T/113: Link balloon should update its position upon external document changes

### LINKED ISSUE #113: Link balloon does not update its position on external changes
It doesn't work only for the balloon of the new link. It works fine with balloon attached to existing link element.

apr-24-2017 19-06-54

A follow-up of https://github.com/ckeditor/ckeditor5-ui/issues/198.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Link balloon should update its position upon external document changes. Closes #113.

### CODE REVIEW

File: src/link.js [hunk 1]
```diff
@@ -244,8 +229,42 @@ export default class Link extends Plugin {
 	 * @return {Promise} A promise resolved when the {@link #formView} {@link module:ui/view~View#init} is done.
 	 */
 	_showPanel( focusInput ) {
+		const editing = this.editor.editing;
+		const showViewDocument = editing.view;
```
Comment (oskarwrobel) [inline src/link.js]: It took me a while to understand why ViewDoc is called `showViewDocument` :)

**Comment by oskarwrobel** [comment]
Works perfectly.
